name: nxfit_sdk
version: 0.2.0
homepage: https://www.neoex.io/
repository: https://github.com/NeoEx-Developer/NxFit-SDK-for-Flutter
description: >
  The NxFit SDK for Flutter provides access to the NxFit REST API to retrieve user health data from the server.

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.0.0"

# It may support multiple platforms, but has only been tested with the following:
platforms:
  android:
  ios:
  web:

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  meta: ^1.9.1
  froom: ^3.0.2
  time_machine: ^0.9.17
  uuid: ^4.4.0
  dio: ^5.8.0+1
  retrofit: ^4.7.2
  json_annotation: ^4.9.0
  sqflite: ^2.4.2
  shared_preferences: ^2.5.3
  rxdart: ^0.28.0
  pretty_dio_logger: ^1.4.0
  copy_with_extension: ^9.1.1
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: ^10.0.4
  froom_generator: ^3.0.2
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.8.0
  copy_with_extension_gen: ^9.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
